db.sql:
    test:
      provider: mysql
#      driver: mysql
      address: user:password@tcp(127.0.0.1:3306)/test?parseTime=true
      trace:
        enabled: true
        time: 500ms
      options:
        max_open_conns: 100
        max_idle_conns: 1
